#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu
#!/usr/bin/env bash
# Connects to server 3.236.220.130 with key in ~/.ssh/school

ssh -i ~/.ssh/school ubuntu@100.25.215.238
